name: Deploy PHP Files
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create .ssh directory
      run: |
        mkdir -p ~/.ssh
    - name: Setup SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    - name: Copy PHP files to VM
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r php/*.php root@gao.lt:/var/www/html/
